package com.entlogic.jgxt.realtime.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2
 * Thu Jun 22 17:41:02 CST 2017
 * Generated source version: 2.2
 * 
 */
 
@WebService(targetNamespace = "http://webServices.realtime.jgxt.entlogic.com/", name = "RtInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface RtInterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://webServices.realtime.jgxt.entlogic.com/", className = "com.entlogic.jgxt.realtime.webservices.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://webServices.realtime.jgxt.entlogic.com/", className = "com.entlogic.jgxt.realtime.webservices.TestResponse")
    @WebMethod
    public java.lang.String test(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "invoke", targetNamespace = "http://webServices.realtime.jgxt.entlogic.com/", className = "com.entlogic.jgxt.realtime.webservices.Invoke")
    @ResponseWrapper(localName = "invokeResponse", targetNamespace = "http://webServices.realtime.jgxt.entlogic.com/", className = "com.entlogic.jgxt.realtime.webservices.InvokeResponse")
    @WebMethod
    public java.lang.String invoke(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "regist", targetNamespace = "http://webServices.realtime.jgxt.entlogic.com/", className = "com.entlogic.jgxt.realtime.webservices.Regist")
    @ResponseWrapper(localName = "registResponse", targetNamespace = "http://webServices.realtime.jgxt.entlogic.com/", className = "com.entlogic.jgxt.realtime.webservices.RegistResponse")
    @WebMethod
    public java.lang.String regist(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0
    );
}
