
/*
 * 
 */

package com.entlogic.jgxt.realtime.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2
 * Thu Jun 22 17:41:02 CST 2017
 * Generated source version: 2.2
 * 
 */


@WebServiceClient(name = "service", 
                  wsdlLocation = "http://10.41.63.17:4092/rti/service?wsdl",
                  targetNamespace = "http://webServices.realtime.jgxt.entlogic.com/") 
public class Service extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webServices.realtime.jgxt.entlogic.com/", "service");
    public final static QName RtInterfaceImpPort = new QName("http://webServices.realtime.jgxt.entlogic.com/", "RtInterfaceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.41.63.17:4092/rti/service?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://10.41.63.17:4092/rti/service?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns RtInterface
     */
    @WebEndpoint(name = "RtInterfaceImpPort")
    public RtInterface getRtInterfaceImpPort() {
        return super.getPort(RtInterfaceImpPort, RtInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RtInterface
     */
    @WebEndpoint(name = "RtInterfaceImpPort")
    public RtInterface getRtInterfaceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices.realtime.jgxt.entlogic.com/", "RtInterfaceImpPort"), RtInterface.class);
    }

}
